#!/bin/bash
# Your job name.
#SBATCH -J DBRC-REPT
#
#SBATCH --ntasks=2
#
# Output files. .out. is for standard output .err. is for the error output. 
#SBATCH -o %x-%j.out # name of the stdout, using the job name (%x), the job number (%j) and the first node (%N)
#
# Maximum expected runtime.  ( 00 Days, 1 hour, 00 minutes, 00 seconds) 
#SBATCH --time=04-00:00:00   
#
# Choose Partition (Queue) 
#SBATCH --partition long 
#
# Mail Options 
#SBATCH --mail-type=FAIL,BEGIN,END    # An email is sent on begin, end, and failure of the job 
#SBATCH --mail-user=heiland@mpi-magdeburg.mpg.de   # E-Mail for notification
#
### END OF THE SLURM SPECIFIC PART ###

# Setup Limit OpenMP 
export OMP_NUM_THREADS=2

# set up the environment (choose whats needed)
# load the modules system 

module load apps/fenics/2018.1

export PYTHONPATH="$PYTHONPATH:/mechthild/home/heiland/lqgbt-oseen"
cd ..

RE=60
NTS=3072  # 12*2**8
PROBLEM=dbrotcyl
MSHLVL=2

SHRTLF=resultsoverview-dbrotcyl.md

INIPERTURB=0.0
FBTYPE=4  # hinf-bt feedback

# NUMPICARDSL=(12 16 20)
# NUMPICARDSL=(12 24 48)

# REPTSL=(-192 -135 -96 -48 -24 -12 -6)
TRUNCATSL=(.512 .128 .064 .045 .032 .008)
REPTSL=(-135)

SCALETEST=25.

GRAMSPATH=grams/
HNFQR=_hinf.mat%outRegulator.Z%outFilter.Z%gam
LQGQR=_lqg.mat%Z_LQG_regulator%Z_LQG_filter

GRAMSFILE=${GRAMSPATH}doublecylinder_re${RE}${LQGQR}
GRAMSFILE=${GRAMSPATH}doublecylinder_re${RE}${HNFQR}
SHRTLF=resultsoverview-2.md

for REPT in "${REPTSL[@]}"; do
    for THRSH in "${TRUNCATSL[@]}"; do
	python3 compscript.py \
	    --problem=${PROBLEM} --mesh=${MSHLVL} \
	    --iniperturb=${INIPERTURB} --RE=${RE} \
	    --closed_loop=${FBTYPE} --pymess \
	    --scaletest=${SCALETEST} --truncat=${THRSH} \
	    --strtogramfacs=${GRAMSFILE} \
	    --Nts=${NTS} \
    	    --ttf_ptre --ttf_value=${REPT} \
	    --shortlogfile=${SHRTLF}
    done
done
